#!/bin/bash

# QUICK START - Docker with PostgreSQL

echo ""
echo "════════════════════════════════════════════════════════════"
echo "  Task Engine API - Docker + PostgreSQL Setup"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "✅ CHANGES COMPLETED:"
echo "   • Switched from H2 to PostgreSQL"
echo "   • Updated application.yaml"
echo "   • Updated pom.xml"
echo "   • Created docker-compose.yml"
echo ""
echo "════════════════════════════════════════════════════════════"
echo ""
echo "🚀 TO START, RUN THESE COMMANDS:"
echo ""
echo "1️⃣  Navigate to project:"
echo "   cd /Users/likhithsabbarapu/Documents/EnterpriseTaskSystem"
echo ""
echo "2️⃣  Start Docker:"
echo "   docker-compose up -d"
echo ""
echo "3️⃣  Wait 30-60 seconds for startup"
echo ""
echo "4️⃣  Open browser:"
echo "   http://localhost:8080/"
echo ""
echo "5️⃣  Login:"
echo "   Username: admin"
echo "   Password: admin123"
echo ""
echo "════════════════════════════════════════════════════════════"
echo ""
echo "📊 POSTGRESQL CREDENTIALS:"
echo ""
echo "   Database: taskdb"
echo "   Username: taskuser"
echo "   Password: taskpass123"
echo "   Host: localhost"
echo "   Port: 5432"
echo ""
echo "════════════════════════════════════════════════════════════"
echo ""
echo "📋 USEFUL DOCKER COMMANDS:"
echo ""
echo "   docker-compose ps              (see containers)"
echo "   docker-compose logs -f         (view logs)"
echo "   docker-compose restart         (restart all)"
echo "   docker-compose down            (stop all)"
echo "   docker-compose down -v         (stop and delete data)"
echo ""
echo "════════════════════════════════════════════════════════════"
echo ""

